# Generated by Django 4.0.6 on 2022-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaskBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(blank=True),
        ),
    ]
