# Generated by Django 4.0.6 on 2022-07-30 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_user_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mask_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('username', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='maskbase',
            name='capability',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='maskbase',
            name='name',
            field=models.CharField(default='none', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='maskbase',
            name='remain',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='maskbase',
            name='total_capacity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
